server:
    port: 8070

spring:
  application:
    name: microservicecloud2020-sidecar
      
eureka:
  client:
    service-url:
      #defaultZone: http://admin:admin@localhost:7001/eureka,http://admin:admin@localhost:7011/eureka
#部署时localhost改为注册中心部署服务器IP
      defaultZone: http://admin:admin@localhost:7001/eureka
      
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json
    
      


